jgnagy/metatron

- Gemfile.lock
- lib/metatron/template.rb
- lib/metatron/version.rb
- spec/metatron/template_spec.rb
This PR enables Metatron to auto-magically determine a resource's kind if it is a subclass of a template. 
In the event that someone defines a resource this way:
```RUBY
class MyConfigMap < Metatron::Templates::ConfigMap
def initialize
super("my-config-map", { foo: :bar })
end
end
```
The kind would then be `kind: MyConfigMap` when it really should be `kind: Secret`.
This PR dynamically gets the closest template's class name and uses it as the kind when it renders.
> Added auto-magical kind detection and tests

- lib/metatron/templates/persistent_volume_claim.rb
Added missing alias methods for `storageClassName` and `accessModes`. This is mostly to be consistent with other resources/templated, but it also makes the `render` method a little cleaner.
> Add alias methods to PersistentVolumeClaim

- Gemfile.lock
- lib/metatron/templates/concerns/pod_producer.rb
- lib/metatron/templates/cron_job.rb
- lib/metatron/templates/daemon_set.rb
- lib/metatron/templates/deployment.rb
- lib/metatron/templates/job.rb
- lib/metatron/templates/pod.rb
- lib/metatron/templates/replica_set.rb
- lib/metatron/templates/stateful_set.rb
- lib/metatron/version.rb
- spec/metatron/templates/cron_job_spec.rb
- spec/metatron/templates/job_spec.rb
- spec/metatron/templates/stateful_set_spec.rb
Moved pod templates to the pod producer using a unified approach, which brings all pod features available in Metatron to all pod producers. Fixes an issue related to `initContainers`  as well.
> Unified pod approach to fix pod templates

- Gemfile.lock
- lib/metatron/sync_controller.rb
- lib/metatron/version.rb
- spec/metatron/sync_controller_spec.rb
Adds support for Metacontroller's webhook [`etag`](https://metacontroller.github.io/metacontroller/api/hook.html#etag-reference) capabilities.
While I was tempted to use Sinatra's OOTB support for ETags via its `etag` helper, it appears that Sinatra is fully RFC7232 compliant, which means it responds with a `412` for `POST` requests that have a `If-None-Match` header that contains the `ETag` value rather than a `304`.
I created https://github.com/metacontroller/metacontroller/issues/850, but in the meantime, I wrote a custom light-weight implementation of ETag support in this PR that should suffice (with testing).
> Add ETag support

- lib/metatron/templates/container.rb
I technically broke the build with my last PR since the tests hang indefinitely if rubocop lints dont pass.
> Fix rubocop complaint.

- Gemfile.lock
- lib/metatron/sync_controller.rb
- lib/metatron/version.rb
- spec/metatron/sync_controller_spec.rb
Now that metacontroller is RFC-compliant, it should be safe for the 0.4.x releases use Sinatra's built-in support for ETags.
Updated tests to reflect the proper 412 return value.
> Switching to sinatra's built-in etag support

- Gemfile.lock
- bin/console
- lib/metatron.rb
- lib/metatron/controller.rb
- lib/metatron/controllers/ping.rb
- lib/metatron/railtie.rb
[Update Gemfile.lock with resolution for x86 linux](https://github.com/jgnagy/metatron/commit/4fc18dfe9b52dfd4320befb1b8780278838c068d)
---
[Add bin/console for easy debugging in irb](https://github.com/jgnagy/metatron/commit/ea94a4d8ff1f8b5b05d637456e26c04447f406b9)
This gets generated with gems created by bundler and I find it really
useful.
---
[Add Metatron::Railtie for Rails integration](https://github.com/jgnagy/metatron/commit/3179c3f028a18c56e8108dfa36f2d6c017d7f44e)
Additionally, change `Metatron::LOGGER` to `Metatron.logger` so that it
can be set to Rails.logger in the Railtie.
> Add Metatron::Railtie for Rails integration

- Rakefile
Fixing the auto-bumping of the gem version to properly zero-out version components.
> Improving bumping of version

- Gemfile.lock
- README.md
- metatron.gemspec
Metatron is a Rack comforming application, which means it will actually work with any Rack compatible server. Making it a runtime dependency is unecessary and will likely just bite us later when a downstream application requires us to bump the puma requirement.
Instead, let's remove it as a runtime dependency. To ensure that the example in the README can still run with puma, it was added to the Gemfile as an example of a "rack compatible server".
> Make puma an optional dependency

- .rubocop.yml
- Gemfile.lock
- README.md
- lib/metatron.rb
- lib/metatron/composite_controller.rb
- lib/metatron/version.rb
- spec/metatron/composite_controller_spec.rb
**BREAKING CHANGE!**
Closes #28
Closes #21 
Moves from a `Metatron::SyncController` to the `Metatron::CompositeController` with the intention of making it easier to also create the [`DecoratorController`](https://metacontroller.github.io/metacontroller/api/decoratorcontroller.html) supported by Metacontroller.
The previous endpoint, which used to be `/` on the mounted `Metatron::SyncController`, is now `/sync` on the mounted `Metatron::CompositeController`. It still relies on the `sync` method defined on the subclass, but now offers `/finalize`and `/customize` on the _same_ controller, allowing easier code reuse.
This aligns with the documentation in the wiki, and this PR updates the repo's `README` to reflect the change. Other documentation (such as the blog mini-series) will need to be …
> Moved to CompositeController

- lib/metatron/controllers/ping.rb
- spec/metatron/controllers/ping_spec.rb
[Add specs for ping controller](https://github.com/jgnagy/metatron/commit/5308def4b42c51235394691ba57aed927374e51a)
---
[Rackify Ping Controller](https://github.com/jgnagy/metatron/commit/9083ae28fd101d3d61c8add3e9f0843265b8fcdf)
This keeps everything that the Sinatra version did previously except for
logging. The use of Rack::Response and Rack::CONTENT_TYPE are to ensure
that we support both versions 2 and 3 of Rack.
> Rackify Ping Controller

- lib/metatron/composite_controller.rb
- lib/metatron/controller.rb
- spec/metatron/composite_controller_spec.rb
[Update CompositeControler specs for Rack 3](https://github.com/jgnagy/metatron/commit/92ded2c006f326098abc0b112ec0f483a8e5af65)
There are two changes being done here:
- adding Rack::Lint to ensure our requests and responses adhere to the
Rack spec (currently 2, but once Sinatra is removed we can run a
matrix against Rack 2 and 3)
- updating some assertions to play nice with Rack 3's downcased headers.
With Rack 2 we can assert with downcased headers as long as we use
methods included in Rack::Utils::HeaderHash. Once we only support Rack
3, then the response headers will be a simple Hash again and these
changes can be partially reverted
---
[Rackify Controller and CompositeController](https://github.com/jgnagy/metatron/commit/18703e1401c4285cafeac46e0434988ed7e23c74)
This removes Sinatra …
> Rackify Controller and CompositeController

- Rakefile
The `bump` rake task should automatically update the `Gemfile.lock` file. This ensures that happens.
> Include gem lockfile update in bump

- Gemfile.lock
- lib/metatron/template.rb
- lib/metatron/templates/cluster_role.rb
- lib/metatron/templates/cluster_role_binding.rb
- lib/metatron/templates/concerns/pod_producer.rb
- lib/metatron/templates/config_map.rb
- lib/metatron/templates/cron_job.rb
- lib/metatron/templates/daemon_set.rb
- lib/metatron/templates/deployment.rb
- lib/metatron/templates/ingress.rb
- lib/metatron/templates/job.rb
- lib/metatron/templates/namespace.rb
- lib/metatron/templates/persistent_volume_claim.rb
- lib/metatron/templates/pod.rb
- lib/metatron/templates/replica_set.rb
- lib/metatron/templates/role.rb
- lib/metatron/templates/role_binding.rb
- lib/metatron/templates/secret.rb
- lib/metatron/templates/service.rb
- lib/metatron/templates/service_account.rb
- lib/metatron/templates/stateful_set.rb
- lib/metatron/version.rb
Refactoring to `base_labels` rather than explicitly creating these same base labels on each template.
This will allow future updates to the base labels if we'd like.
> Refactor template.rb to use base_labels

- Gemfile.lock
- lib/metatron/templates/service.rb
- lib/metatron/version.rb
aliases do not work with subclassing and redefining methods, replacing them with methods instead
> replace alias with method definitions

- lib/metatron/templates/persistent_volume_claim.rb
- spec/metatron/templates/persistent_volume_claim_spec.rb
Closes #41
Adds support for `spec.dataSource` and `spec.dataSourceRef` to the `PersistentVolumeClaim` template.
Includes some validations on supported keys plus minimal testing.
> Adds dataSource and dataSourceRef to PVCs

- lib/metatron/templates/concerns/pod_producer.rb
- spec/metatron/templates/pod_spec.rb
Adds support to pod producing templates to allow setting Pod's `spec.priorityClassName`.
> Add support for pod priority class name

- lib/metatron/template.rb
- lib/metatron/templates/concerns/pod_producer.rb
- lib/metatron/templates/daemon_set.rb
- lib/metatron/templates/deployment.rb
- lib/metatron/templates/replica_set.rb
- lib/metatron/templates/stateful_set.rb
- spec/metatron/template_spec.rb
- spec/metatron/templates/daemon_set_spec.rb
- spec/metatron/templates/deployment_spec.rb
- spec/metatron/templates/replica_set_spec.rb
- spec/metatron/templates/stateful_set_spec.rb
Resolves #72 
Base labels can now be completely overridden, even at a per template instance level, as opposed to the previous behavior only allowing changing the label namespace at a global level.
Pod selector match labels, used by pod producers, must now be explicitly set rather than assuming and merging in `additional_pod_labels`. This allows adding pods labels in pod producer templates (Deployment, StatefulSet, etc.) without those automatically being used to match.
> Better handling of automated template pod labels

- README.md
- lib/metatron/controllers/ping.rb
- spec/metatron/controllers/ping_spec.rb
`Metatron::Controllers::Ping` can now be used just like other Rack apps, either as a class or via `#new`.
Also made some minor README updates
> More Options for Ping Controller

- Gemfile.lock
- lib/metatron.rb
- lib/metatron/templates/secret.rb
- lib/metatron/templates/service.rb
- metatron.gemspec
- spec/metatron/templates/secret_spec.rb
- spec/metatron/templates/service_spec.rb
This change hides the default Service `publishNotReadyAddresses` attribute when set to `false` since this caused repeated updates to Service resources resulting from the template.
Also updates `Secret` to support `data` for supplying Base64-encoded values. This is a **breaking change** as all values are forced to be Base64-encoded (meaning only `data` will show up in the rendered Secret). This is also in the service of preventing repeated updates to Secret resources caused by applying `stringData` and getting back `data` fro the Kubernetes API.
Resolves #78.
> Refactoring Service and Secret templates to be less noisy

- lib/metatron/templates/cron_job.rb
- spec/metatron/templates/cron_job_spec.rb
Adding support for job-level `activeDeadlineSeconds` and `ttlSecondsAfterFinished`, as well as support for `timeZone` on the cronjob spec.
> Add additional features to cron job template
